// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package assessmenet

import (
	"github.com/google/syzkaller/pkg/aflow"
	"github.com/google/syzkaller/pkg/aflow/action/kernel"
	"github.com/google/syzkaller/pkg/aflow/ai"
	"github.com/google/syzkaller/pkg/aflow/tool/codesearcher"
	"github.com/google/syzkaller/pkg/aflow/tool/grepper"
)

type moderationInputs struct {
	BugTitle     string
	CrashReport  string
	KernelRepo   string
	KernelCommit string
	KernelConfig string
}

func init() {
	aflow.Register[moderationInputs, ai.ModerationOutputs](
		ai.WorkflowModeration,
		"assess if a bug report is consistent and actionable or not",
		&aflow.Flow{
			Root: aflow.Pipeline(
				kernel.Checkout,
				kernel.Build,
				codesearcher.PrepareIndex,
				&aflow.LLMAgent{
					Name:  "expert",
					Model: aflow.GoodBalancedModel,
					Reply: "Explanation",
					Outputs: aflow.LLMOutputs[struct {
						Actionable bool `jsonschema:"If the report is actionable or not."`
					}](),
					TaskType:    aflow.FormalReasoningTask,
					Instruction: moderationInstruction,
					Prompt:      moderationPrompt,
					Tools:       aflow.Tools(codesearcher.Tools, grepper.Tool),
				},
				&aflow.LLMAgent{
					Name:  "skeptic",
					Model: aflow.GoodBalancedModel,
					Outputs: aflow.LLMOutputs[struct {
						Confident bool `jsonschema:"If the expert's analysis is correct and well-supported or not."`
					}](),
					TaskType:    aflow.FormalReasoningTask,
					Instruction: moderationSkepticInstruction,
					Prompt:      moderationSkepticPrompt,
				},
			),
		},
	)
}

const moderationInstruction = `
You are an experienced Linux kernel developer tasked with determining if the given kernel bug
report is actionable or not. Actionable means that it contains enough info to root cause
the underlying bug, and that the report is self-consistent and makes sense, rather than
e.g. a one-off nonsensical crash induced by a previous memory corruption.

{{if titleIsUAF .BugTitle}}
The bug report is about a use-after-free bug generated by KASAN tool.
It should contain 3 stack traces: the bad memory access stack, the heap block allocation stack,
and the heap block free stack. If the report does not contain 3 stacks, it's not actionable.

All 3 stack traces should be related to the same object type,
and usually be in the same kernel subsystem (at least leaf stack frames).
An example of an actionable and consistent report would be: first access stack relates
to an access to a field of struct Foo, allocation/free stacks relate to allocation/free
of the struct Foo.
In inconsistent/nonsensical reports an access may be to a struct Foo, but allocation
stack allocates a different structure in a different subsystem.
Look for other suspicious signals/inconsistencies that can make this report hard to
debug/understand. 
{{end}}

In the final reply explain why you think the report is self-consistent and actionable,
or why it's inconsistent and/or not actionable.

Use the provided tools to confirm any assumptions, variables/fields being accessed, etc.
In particular, don't make assumptions about the kernel source code,
use codesearch tools to read the actual source code.
`

const moderationPrompt = `
The bug report is:

{{.CrashReport}}
`

const moderationSkepticInstruction = `
You are reviewing a kernel developer's assessment of a bug report.
You did NOT write this assessment. Evaluate it critically and independently.

Set Confident to true only if the reasoning is sound, the conclusion is clearly
supported by evidence, and there are no significant gaps or unverified assumptions.
Set Confident to false if there is meaningful doubt about the correctness of the verdict.
`

const moderationSkepticPrompt = `
The original bug report:
{{.CrashReport}}

The expert concluded the report is {{if .Actionable}}actionable{{else}}not actionable{{end}}.

Their explanation:
{{.Explanation}}

Is the conclusion well-supported? Are you confident in it?
`
