# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: fetch-kernels-cron
spec:
  # Three times per day.
  schedule: "0 */8 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    workflowTemplateRef:
      name: fetch-kernels-workflow-template
