# Copyright 2017 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

# For documentation see:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "mod:"
  assignees:
    - "tarasmadan"
