# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  name: reporter-service
spec:
  selector:
    app: controller
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
