# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/google/syzkaller/pkg/gcs:
    interfaces:
      Client:
  github.com/google/syzkaller/pkg/covermerger:
    interfaces:
      FileVersProvider:
  github.com/google/syzkaller/pkg/coveragedb/spannerclient:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
    interfaces:
      SpannerClient:
      ReadOnlyTransaction:
      RowIterator:
      Row:
  github.com/google/syzkaller/pkg/rpcserver:
    interfaces:
      Manager:
  github.com/google/syzkaller/vm/proxyapp/proxyrpc:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
    interfaces:
      ProxyAppInterface:
  github.com/google/syzkaller/vm/proxyapp:
    config:
      structname: "SubProcessCmd"
    interfaces:
      subProcessCmd:
