# Copyright 2017 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

# Vendor file for github.com/golang/dep.
# Dependencies can be updated with:
# go get github.com/golang/dep
# dep ensure -update

[[constraint]]
  branch = "master"
  name = "cloud.google.com/go"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"
