ALTER TABLE Jobs ADD COLUMN ParentJobID STRING(36);
ALTER TABLE Jobs ADD CONSTRAINT FK_Jobs_ParentJob FOREIGN KEY (ParentJobID) REFERENCES Jobs (ID);
DROP INDEX JobCommentsForIteration;
ALTER TABLE JobComments DROP COLUMN Processed;
ALTER TABLE Jobs DROP COLUMN ParentReportingID;
ALTER TABLE JobReporting DROP COLUMN Version;
ALTER TABLE Jobs ADD COLUMN Version INT64;
