ALTER TABLE Jobs DROP CONSTRAINT TypeEnum;
ALTER TABLE Jobs DROP CONSTRAINT FK_JobWorkflow;
ALTER TABLE PatchingJobs DROP CONSTRAINT TypeEnum;
ALTER TABLE PatchingJobs DROP CONSTRAINT FK_PatchingJobJob;
ALTER TABLE TrajectorySpans DROP CONSTRAINT TypeEnum;
ALTER TABLE TrajectorySpans DROP CONSTRAINT FK_EventJob;

DROP TABLE Workflows;
DROP TABLE Jobs;
DROP TABLE PatchingJobs;
DROP TABLE TrajectorySpans;
