// Package kfuzztest exposes functions discovering KFuzzTest test cases from a
// vmlinux binary and parsing them into syzkaller-compatible formats.
// The general flow includes:
//   - Creating an Extractor that extracts these test cases from the binary
//   - Creating a Builder that takes the extractor's output and returns some
//     compatible encoding of the test cases that were discovered
package kfuzztest

import (
	"fmt"
	"os"
	"path"

	"github.com/google/syzkaller/pkg/ast"
	"github.com/google/syzkaller/pkg/compiler"
	"github.com/google/syzkaller/pkg/kcov"
	"github.com/google/syzkaller/pkg/mgrconfig"
	"github.com/google/syzkaller/prog"
	"github.com/google/syzkaller/sys/targets"
)

type SyzField struct {
	Name     string
	TypeName string
}

type SyzStruct struct {
	Name   string
	Fields []SyzField
}

type SyzFunc struct {
	Name            string
	InputStructName string
}

type ConstraintType uint8

const (
	ExpectEq ConstraintType = iota
	ExpectNe
	ExpectLt
	ExpectLe
	ExpectGt
	ExpectGe
	ExpectInRange
)

func (c ConstraintType) String() string {
	return [...]string{"EXPECT_EQ", "EXPECT_NE", "EXPECT_LT", "EXPECT_LE", "EXPECT_GT", "EXPECT_GE", "EXPECT_IN_RANGE"}[c]
}

type SyzConstraint struct {
	InputType string
	FieldName string
	Value1    uintptr
	Value2    uintptr
	ConstraintType
}

type AnnotationAttribute uint8

const (
	AttributeLen AnnotationAttribute = iota
	AttributeString
	AttributeArray
)

func (a AnnotationAttribute) String() string {
	return [...]string{"ATTRIBUTE_LEN", "ATTRIBUTE_STRING", "ATTRIBUTE_ARRAY"}[a]
}

type SyzAnnotation struct {
	InputType       string
	FieldName       string
	LinkedFieldName string
	Attribute       AnnotationAttribute
}

// ExtractDescription returns a syzlang description of all discovered KFuzzTest
// targets, or an error on failure.
func ExtractDescription(vmlinuxPath string) (string, error) {
	extractor, err := NewExtractor(vmlinuxPath)
	if err != nil {
		return "", err
	}
	eRes, err := extractor.ExtractAll()
	if err != nil {
		return "", err
	}
	builder := NewBuilder(eRes.Funcs, eRes.Structs, eRes.Constraints, eRes.Annotations)
	return builder.EmitSyzlangDescription()
}

// extractProg extracts a compiler.Prog from VMLinux containing all of the
// discovered KFuzzTest target definitions, resources, and types.
func extractProg(vmlinuxPath string) (*compiler.Prog, error) {
	desc, err := ExtractDescription(vmlinuxPath)
	if err != nil {
		return nil, err
	}

	var astError error
	eh := func(pos ast.Pos, msg string) {
		astError = fmt.Errorf("AST error: %v: %v\n", pos, msg)
	}
	descAst := ast.Parse([]byte(desc), "kfuzztest-autogen", eh)
	if astError != nil {
		return nil, astError
	}
	if descAst == nil {
		return nil, fmt.Errorf("failed to build AST for program")
	}

	target := targets.Get(targets.Linux, targets.AMD64)
	program := compiler.Compile(descAst, make(map[string]uint64), target, eh)
	if program == nil {
		return nil, fmt.Errorf("failed to compile extracted KFuzzTest target")
	}

	prog.RestoreLinks(program.Syscalls, program.Resources, program.Types)
	return program, nil
}

// EnableKFuzzTargets enabled KFuzzTest targets that are discovered in the
// vmlinux binary pointed to by the manager configuation. This assumes that
// the config has lready been loaded, for example via cfg.LoadFile in the
// main function of the syz-manager program. Returns a list of new KFuzzTest
// syscalls on success, or an error on failure.
func EnableKFuzzTargets(cfg *mgrconfig.Config) ([]*prog.Syscall, error) {
	vmLinuxPath := path.Join(cfg.KernelObj, "vmlinux")
	newProg, err := extractProg(vmLinuxPath)
	if err != nil || newProg == nil {
		return []*prog.Syscall{}, err
	}

	cfg.Target.Extend(newProg.Syscalls, newProg.Types, newProg.Resources)
	kFuzzTestCalls := []*prog.Syscall{}
	for _, syscall := range newProg.Syscalls {
		// The program generated by extractProg contains a certain number of
		// builtins, which we want to filer out.
		if !syscall.Attrs.KFuzzTest {
			continue
		}
		kFuzzTestCalls = append(kFuzzTestCalls, syscall)
		cfg.EnabledSyscalls = append(cfg.EnabledSyscalls, syscall.Name)
		cfg.Syscalls = append(cfg.Syscalls, syscall.ID)
	}
	return kFuzzTestCalls, nil
}

func ActivateKFuzzTargets(vmLinuxPath string, target *prog.Target, enabledCalls *map[*prog.Syscall]bool) error {
	newProg, err := extractProg(vmLinuxPath)
	// If newProg is nil, then err is always non-nil.
	if err != nil {
		return err
	}

	// We can only enable the new syscalls if the ID was found as this
	// description as well as it's corresponding pseudo-syscall need to
	// be built into syzkaller.
	target.Extend(newProg.Syscalls, newProg.Types, newProg.Resources)

	if enabledCalls != nil {
		// Enable discovered syscalls.
		for _, syscall := range newProg.Syscalls {
			(*enabledCalls)[syscall] = true
		}
	}
	return nil
}

func ExecKFuzzTestCallLocal(st *kcov.KCOVState, call *prog.Call) ([]uintptr, error) {
	if !call.Meta.Attrs.KFuzzTest {
		return []uintptr{}, fmt.Errorf("call is not a KFuzzTest call")
	}
	testName, isKFuzzTest := GetTestName(call.Meta)
	if !isKFuzzTest {
		return []uintptr{}, fmt.Errorf("tried to execute a syscall that wasn't syz_kfuzztest_run")
	}

	dataArg, ok := call.Args[1].(*prog.PointerArg)
	if !ok {
		return []uintptr{}, fmt.Errorf("second arg for syz_kfuzztest_run should be a pointer")
	}
	finalBlob := prog.MarshallKFuzztestArg(dataArg.Res)
	inputPath := GetInputFilepath(testName)

	res := st.Trace(func() error { return os.WriteFile(inputPath, finalBlob, 0644) })
	return res.Coverage, res.Result
}
