apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - :9001
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - name: "ui-address"
      port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30000
    - name: "console-address"
      port: 9001
      targetPort: 9001
      protocol: TCP
      nodePort: 30001
---
apiVersion: v1
kind: Secret
metadata:
  name: my-minio-cred
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
