// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package syzlang

import (
	"encoding/json"
	"errors"

	"github.com/google/syzkaller/pkg/aflow"
	"github.com/google/syzkaller/pkg/aflow/action/crash"
	aflow_syzlang "github.com/google/syzkaller/pkg/aflow/syzlang"
	"github.com/google/syzkaller/prog"
	_ "github.com/google/syzkaller/sys"
)

var Reproduce = aflow.NewFuncTool("reproduce-crash", reproduce, `
Tool evaluates whether the given syz repro program crashes the kernel.
It will compile the program and execute it in a VM.
You MUST use this tool to verify your generated syz repro program.
`)

type ReproduceArgs struct {
	ReproSyz string `jsonschema:"Syz program to verify and execute."`
	Sandbox  string `jsonschema:"Sandbox to use for execution (none/setuid/namespace/android)."`
}

type ReproduceResult struct {
	ReproducedBugTitle    string `jsonschema:"Bug title triggered by the reproducer."`
	ReproducedCrashReport string `jsonschema:"Crash report generated by the reproducer."`
	ExecutionCachedID     string `jsonschema:"Cached ID. Pass to coverage tools to explore executed code."`
}

type reproduceState struct {
	TargetOS     string
	TargetArch   string
	KernelSrc    string
	KernelCommit string
	KernelConfig string
	KernelObj    string
	Image        string
	Type         string
	VM           json.RawMessage
	Syzkaller    string
}

func (s reproduceState) targetConfig() crash.TargetConfig {
	return crash.TargetConfig{
		TargetArch:   s.TargetArch,
		Syzkaller:    s.Syzkaller,
		Image:        s.Image,
		Type:         s.Type,
		VM:           s.VM,
		KernelSrc:    s.KernelSrc,
		KernelObj:    s.KernelObj,
		KernelCommit: s.KernelCommit,
		KernelConfig: s.KernelConfig,
	}
}

func (s reproduceState) toReproduceArgs(reproSyz string) crash.ReproduceArgs {
	return crash.ReproduceArgs{
		TargetConfig: s.targetConfig(),
		ReproSyz:     reproSyz,
	}
}

func (s reproduceState) toExecuteSeedArgs(
	baseSeed aflow_syzlang.BaseTestSeed, generatedSyz string) crash.ExecuteSeedArgs {
	return crash.ExecuteSeedArgs{
		TargetConfig: s.targetConfig(),
		BaseSeed:     baseSeed,
		GeneratedSyz: generatedSyz,
	}
}

func reproduce(ctx *aflow.Context, state reproduceState, args ReproduceArgs) (ReproduceResult, error) {
	if args.ReproSyz == "" {
		return ReproduceResult{}, aflow.BadCallError("syz program cannot be empty")
	}

	pt, err := prog.GetTarget(state.TargetOS, state.TargetArch)
	if err != nil {
		return ReproduceResult{}, err
	}
	_, err = pt.Deserialize([]byte(args.ReproSyz), prog.Strict)
	if err != nil {
		return ReproduceResult{}, aflow.BadCallError("%v", err)
	}

	if state.Image == "" || state.VM == nil {
		// VM configuration is missing, we can only verify the program compiles.
		// This is required for unit tests that pass an empty state.
		return ReproduceResult{}, nil
	}

	reproArgs := state.toReproduceArgs(args.ReproSyz)
	reproArgs.TargetConfig.Sandbox = args.Sandbox

	if err := reproArgs.Validate(); err != nil {
		return ReproduceResult{}, aflow.BadCallError("invalid configuration: %v", err)
	}

	testRes, cachedID, err := crash.ReproduceFuncWithCoverage(ctx, reproArgs, true)
	if err != nil {
		if errors.Is(err, crash.ErrDidNotCrash) {
			return ReproduceResult{ExecutionCachedID: cachedID}, nil
		}
		return ReproduceResult{}, err
	}

	return ReproduceResult{
		ReproducedBugTitle:    testRes.ReproducedBugTitle,
		ReproducedCrashReport: testRes.ReproducedCrashReport,
		ExecutionCachedID:     cachedID,
	}, nil
}
