// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package syzlang

import (
	"github.com/google/syzkaller/pkg/aflow"
	"github.com/google/syzkaller/prog"
	_ "github.com/google/syzkaller/sys"
)

var Reproduce = aflow.NewFuncTool("crash-reproducer", reproduce, `
Tool evaluates whether the given repro program crashes the kernel.
It will compile the program and execute it in a VM.
`)

type ReproduceArgs struct {
	CandidateReproSyz string `jsonschema:"Syz program to verify and execute."`
}

type ReproduceResult struct {
	ReproducedBugTitle    string `jsonschema:"Bug title triggered by the reproducer."`
	ReproducedCrashReport string `jsonschema:"Crash report generated by the reproducer."`
}

func reproduce(ctx *aflow.Context, state struct{}, args ReproduceArgs) (ReproduceResult, error) {
	pt, err := prog.GetTarget("linux", "amd64")
	if err != nil {
		return ReproduceResult{}, err
	}
	_, err = pt.Deserialize([]byte(args.CandidateReproSyz), prog.Strict)
	if err != nil {
		return ReproduceResult{}, aflow.BadCallError("%v", err)
	}
	// The program compiled successfully. For now, pretend it didn't reproduce any crash.
	return ReproduceResult{}, nil
}
