# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

resources:
  - network-deny-all.yaml
  - network-policy-controller.yaml
  - network-policy-git-access.yaml
