# Copyright 2026 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: syz-manager-config
  namespace: syzkube
data:
  manager.cfg: |
    {
      "name": "syz-k8s-manager",
      "target": "linux/amd64",
      "http": "0.0.0.0:50002",
      "workdir": "/workdir",
      "syzkaller": "/syzkaller",
      "kernel_obj": "/syzkaller/assets",
      "image": "/disk.raw",
      "sshkey": "/syzkaller/assets/id_rsa",
      "sandbox": "none",
      "type": "qemu",
      "procs": 2,
      "cover": true,
      "dashboard_client": "local_ui_client",
      "dashboard_addr": "http://syz-dashboard.syzkube.svc.cluster.local:8080",
      "dashboard_key": "localuipasswordlocaluipasswordlocaluipassword",
      "tag": "upstream-k8s-build-1",
      "vm": {
        "count": 2,
        "kernel": "/syzkaller/assets/bzImage",
        "cpu": 1,
        "mem": 2048,
        "qemu_args": "-enable-kvm",
        "cmdline": "root=/dev/sda1 console=ttyS0"
      }
    }
