# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migrate-job-
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: db-mgmt
    spec:
      serviceAccountName: gke-db-admin-ksa
      containers:
      - name: migrate
        image: ${IMAGE_PREFIX}db-mgmt:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: global-config-env
        args: ["migrate"]
      restartPolicy: Never
