// Code generated by "stringer -type Status"; DO NOT EDIT.

package queue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[ExecFailure-1]
	_ = x[Crashed-2]
	_ = x[Restarted-3]
	_ = x[Hanged-4]
}

const _Status_name = "SuccessExecFailureCrashedRestartedHanged"

var _Status_index = [...]uint8{0, 7, 18, 25, 34, 40}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
