# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  executor: |
      env:
         - name: STORAGE_EMULATOR_HOST
           value: http://fake-gcs-server.default.svc.cluster.local:4443
