# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-service-ksa
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor-ksa
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-controller-ksa
  namespace: argo

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-db-admin-ksa
  namespace: default
