// AUTOGENERATED FILE

#if defined(__x86_64__) || 0
#define GOARCH "amd64"
#define SYZ_REVISION "640bc9ab193d2488d41793c10c5a44bab3ad33f9"
#define __NR_syz_mmap 1000000

unsigned syscall_count = 5;
call_t syscalls[] = {
    {"syz_mmap", 1000000, (syscall_t)syz_mmap},
    {"zx_handle_close", 0, (syscall_t)zx_handle_close},
    {"zx_handle_duplicate", 0, (syscall_t)zx_handle_duplicate},
    {"zx_handle_replace", 0, (syscall_t)zx_handle_replace},
    {"zx_time_get", 0, (syscall_t)zx_time_get},

};
#endif

#if defined(__aarch64__) || 0
#define GOARCH "arm64"
#define SYZ_REVISION "8c364809f3ccf951f9c9ac974a817dfaf8d1713c"
#define __NR_syz_mmap 1000000

unsigned syscall_count = 5;
call_t syscalls[] = {
    {"syz_mmap", 1000000, (syscall_t)syz_mmap},
    {"zx_handle_close", 0, (syscall_t)zx_handle_close},
    {"zx_handle_duplicate", 0, (syscall_t)zx_handle_duplicate},
    {"zx_handle_replace", 0, (syscall_t)zx_handle_replace},
    {"zx_time_get", 0, (syscall_t)zx_time_get},

};
#endif
