CREATE TABLE SeriesStats (
    ID STRING(36) NOT NULL,
    StatsVersion STRING(36) NOT NULL,
    PreventedBugs INT64 NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    CONSTRAINT FK_SeriesStats_Series FOREIGN KEY (ID) REFERENCES Series (ID)
) PRIMARY KEY (ID),
  INTERLEAVE IN PARENT Series ON DELETE CASCADE;
