CREATE TABLE Jobs (
    ID STRING(36) NOT NULL,
    Type STRING(128) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    Reporter STRING(256) NOT NULL,
    User STRING(512) NOT NULL,
    ExtID STRING(512) NOT NULL,
    PatchURI STRING(512) NOT NULL,
    Cc ARRAY<STRING(512)>,
    ReportID STRING(36) NOT NULL,
    CONSTRAINT FK_JobSessionReport FOREIGN KEY (ReportID) REFERENCES SessionReports (ID),
    CONSTRAINT JobTypeEnum CHECK (Type IN ('patch_test')),
) PRIMARY KEY (ID);

CREATE INDEX JobsByExtID ON Jobs(ExtID);

ALTER TABLE Sessions ADD COLUMN JobID STRING(36);
ALTER TABLE Sessions ADD CONSTRAINT FK_SessionJob FOREIGN KEY (JobID) REFERENCES Jobs (ID);
