// Code generated by goyacc -o strace.go -p Strace -v= strace.y. DO NOT EDIT.

//line strace.y:2
// Copyright 2018 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

//go:build !codeanalysis
// +build !codeanalysis

package parser

import __yyfmt__ "fmt"

//line strace.y:7

//line strace.y:13
type StraceSymType struct {
	yys             int
	data            string
	val_int         int64
	val_double      float64
	val_ret_type    int64
	val_uint        uint64
	val_constant    Constant
	val_identifiers []*BufferType
	val_buf_type    *BufferType
	val_group_type  *GroupType
	val_type        IrType
	val_types       []IrType
	val_syscall     *Syscall
}

const STRING_LITERAL = 57346
const IPV6 = 57347
const IDENTIFIER = 57348
const FLAG = 57349
const DATETIME = 57350
const SIGNAL_PLUS = 57351
const SIGNAL_MINUS = 57352
const MAC = 57353
const INT = 57354
const UINT = 57355
const DOUBLE = 57356
const QUESTION = 57357
const ARROW = 57358
const OR = 57359
const AND = 57360
const LOR = 57361
const TIMES = 57362
const LAND = 57363
const LEQUAL = 57364
const ONESCOMP = 57365
const LSHIFT = 57366
const RSHIFT = 57367
const NOT = 57368
const MINUS = 57369
const PLUS = 57370
const COMMA = 57371
const LBRACKET = 57372
const RBRACKET = 57373
const LBRACKET_SQUARE = 57374
const RBRACKET_SQUARE = 57375
const LPAREN = 57376
const RPAREN = 57377
const EQUALS = 57378
const UNFINISHED = 57379
const RESUMED = 57380
const NULL = 57381
const EQUALAT = 57382
const COLON = 57383
const FORWARDSLASH = 57384
const LOWEST = 57385
const NOFLAG = 57386
const NEG = 57387

var StraceToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING_LITERAL",
	"IPV6",
	"IDENTIFIER",
	"FLAG",
	"DATETIME",
	"SIGNAL_PLUS",
	"SIGNAL_MINUS",
	"MAC",
	"INT",
	"UINT",
	"DOUBLE",
	"QUESTION",
	"ARROW",
	"OR",
	"AND",
	"LOR",
	"TIMES",
	"LAND",
	"LEQUAL",
	"ONESCOMP",
	"LSHIFT",
	"RSHIFT",
	"NOT",
	"MINUS",
	"PLUS",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LBRACKET_SQUARE",
	"RBRACKET_SQUARE",
	"LPAREN",
	"RPAREN",
	"EQUALS",
	"UNFINISHED",
	"RESUMED",
	"NULL",
	"EQUALAT",
	"COLON",
	"FORWARDSLASH",
	"LOWEST",
	"NOFLAG",
	"NEG",
}

var StraceStatenames = [...]string{}

const StraceEofCode = 1
const StraceErrCode = 2
const StraceInitialStackSize = 16

//line yacctab:1
var StraceExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const StracePrivate = 57344

const StraceLast = 514

var StraceAct = [...]uint8{
	18, 68, 104, 46, 15, 7, 46, 44, 19, 103,
	11, 10, 45, 130, 46, 8, 44, 117, 89, 42,
	102, 54, 65, 45, 64, 41, 45, 44, 43, 55,
	44, 43, 58, 59, 45, 12, 6, 40, 44, 63,
	60, 61, 62, 119, 100, 66, 2, 116, 73, 74,
	75, 76, 4, 95, 5, 97, 77, 78, 79, 80,
	81, 82, 83, 110, 113, 55, 90, 57, 34, 114,
	115, 101, 99, 51, 106, 107, 51, 39, 3, 67,
	94, 108, 109, 52, 53, 121, 105, 27, 96, 26,
	51, 42, 131, 92, 84, 112, 38, 52, 37, 111,
	17, 16, 112, 0, 112, 118, 123, 0, 51, 70,
	71, 120, 49, 50, 1, 52, 53, 112, 0, 9,
	112, 112, 125, 123, 72, 112, 124, 123, 112, 127,
	123, 21, 132, 22, 25, 23, 28, 29, 24, 28,
	29, 31, 0, 0, 31, 70, 71, 56, 91, 0,
	20, 33, 0, 0, 33, 0, 14, 27, 32, 26,
	72, 32, 36, 30, 35, 0, 30, 110, 113, 70,
	71, 0, 69, 114, 115, 0, 110, 113, 106, 107,
	0, 0, 114, 115, 72, 108, 109, 106, 107, 0,
	105, 27, 0, 26, 108, 109, 129, 0, 0, 105,
	27, 0, 26, 111, 0, 128, 21, 0, 22, 25,
	23, 0, 111, 24, 28, 29, 0, 0, 0, 31,
	0, 0, 0, 0, 0, 20, 0, 0, 0, 33,
	0, 14, 27, 0, 26, 0, 32, 126, 110, 113,
	0, 30, 0, 0, 114, 115, 0, 0, 0, 106,
	107, 0, 0, 0, 0, 0, 108, 109, 0, 0,
	0, 105, 27, 0, 26, 0, 0, 122, 21, 0,
	22, 25, 23, 0, 111, 24, 28, 29, 0, 0,
	0, 31, 0, 0, 0, 0, 0, 20, 0, 0,
	0, 33, 0, 14, 27, 0, 26, 0, 32, 93,
	0, 0, 21, 30, 22, 25, 23, 0, 0, 24,
	28, 29, 0, 0, 0, 31, 0, 0, 0, 0,
	0, 20, 0, 0, 0, 33, 0, 86, 27, 87,
	26, 21, 32, 22, 25, 23, 0, 30, 24, 28,
	29, 0, 0, 0, 31, 0, 0, 0, 0, 0,
	20, 0, 0, 0, 33, 0, 14, 27, 0, 26,
	85, 32, 0, 0, 0, 21, 30, 22, 25, 23,
	0, 0, 24, 28, 29, 0, 0, 0, 31, 0,
	0, 0, 0, 0, 20, 0, 0, 0, 33, 0,
	14, 27, 0, 26, 0, 32, 13, 110, 113, 0,
	30, 0, 0, 114, 115, 0, 0, 0, 106, 107,
	0, 0, 0, 0, 0, 108, 109, 0, 0, 0,
	105, 27, 21, 26, 22, 25, 23, 0, 0, 24,
	28, 29, 0, 111, 0, 31, 47, 48, 0, 51,
	0, 20, 0, 49, 50, 33, 52, 53, 27, 98,
	26, 21, 32, 22, 25, 23, 0, 30, 24, 28,
	29, 0, 0, 0, 31, 0, 0, 28, 29, 0,
	20, 0, 31, 0, 33, 0, 0, 27, 56, 26,
	0, 32, 33, 0, 0, 27, 30, 26, 0, 32,
	47, 48, 0, 51, 30, 0, 0, 49, 50, 0,
	52, 53, 0, 48, 0, 51, 0, 0, 88, 49,
	50, 0, 52, 53,
}

var StracePact = [...]int16{
	40, -1000, 20, -1, 40, -28, 0, 361, 38, -1000,
	127, 61, 1, -11, 447, -10, -1000, -1000, -1000, 419,
	455, -1000, 35, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 124, 124, 124, 447, -1000, -12, -1000, -14, -1000,
	64, 157, -10, 447, 447, 447, 447, 124, 124, 124,
	124, 124, 124, 124, -1000, -1000, 124, 87, 327, 298,
	485, 473, -1000, -13, 133, 81, 264, -1000, 46, -1000,
	-1000, -1000, 76, -2, -1000, -33, -24, 485, 88, 56,
	56, -1000, 53, 70, 22, -1000, 418, -1000, -1000, 43,
	37, -1000, -1000, -16, 391, 13, -1000, -19, -1000, -1000,
	9, 391, 73, 232, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 391, 447, 202, 391,
	170, -1000, -1000, -1000, 161, -33, -23, 57, -1000, -1000,
	97, -1000, -1000,
}

var StracePgo = [...]int8{
	0, 114, 1, 101, 0, 8, 2, 9, 4, 100,
	5,
}

var StraceR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 7, 7, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 2,
	2, 2, 10, 10, 10, 8, 8, 8, 8, 8,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 4, 4, 4, 9, 9, 9,
	9, 9, 3, 3, 3, 3, 3,
}

var StraceR2 = [...]int8{
	0, 4, 5, 4, 6, 8, 5, 10, 5, 8,
	9, 6, 6, 10, 9, 2, 1, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 0, 3, 2, 1, 1, 1, 1, 2,
	1, 1, 1, 3, 2, 3, 3, 3, 3, 3,
	3, 3, 2, 2, 3, 3, 4, 3, 3, 3,
	3, 6, 1, 1, 1, 1, 1,
}

var StraceChk = [...]int16{
	-1000, -1, 6, 38, 12, 34, 37, -10, 16, -1,
	-10, 38, 35, 35, 29, -8, -3, -9, -4, -5,
	23, 4, 6, 8, 11, 7, 32, 30, 12, 13,
	39, 17, 34, 27, 30, 37, 35, 37, 35, 16,
	36, 36, -8, 41, 40, 36, 16, 17, 18, 24,
	25, 20, 27, 28, -4, -5, 23, 32, -10, -10,
	-5, -5, -5, -8, 36, 36, -10, 15, -2, 15,
	12, 13, 27, -8, -8, -8, -8, -5, -5, -5,
	-5, -5, -5, -5, 7, 33, 29, 31, 35, 31,
	-2, 15, 12, 35, 34, 7, 12, 33, 31, 29,
	7, 34, 36, -7, -6, 29, 17, 18, 24, 25,
	6, 42, -4, 7, 12, 13, 34, 36, -10, 34,
	-7, 12, 35, -6, -7, -8, 35, -7, 35, 35,
	36, 35, -2,
}

var StraceDef = [...]int8{
	0, -2, 0, 32, 0, 32, 0, 0, 0, 15,
	0, 0, 0, 0, 0, 34, 35, 36, 37, 38,
	0, 62, 63, 64, 65, 66, 32, 32, 40, 41,
	42, 0, 0, 0, 0, 1, 0, 3, 0, 32,
	0, 0, 33, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 39, 52, 0, 0, 0, 0,
	44, 0, 53, 0, 0, 0, 0, 2, 6, 8,
	29, 30, 0, 57, 58, 59, 60, 43, 45, 46,
	47, 49, 50, 51, 0, 54, 0, 55, 48, 0,
	11, 12, 4, 0, 0, 0, 31, 0, 56, 32,
	0, 0, 0, 0, 16, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 0, 0, 0, 0,
	0, 5, 9, 17, 0, 61, 0, 0, 14, 10,
	0, 13, 7,
}

var StraceTok1 = [...]int8{
	1,
}

var StraceTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45,
}

var StraceTok3 = [...]int8{
	0,
}

var StraceErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	StraceDebug        = 0
	StraceErrorVerbose = false
)

type StraceLexer interface {
	Lex(lval *StraceSymType) int
	Error(s string)
}

type StraceParser interface {
	Parse(StraceLexer) int
	Lookahead() int
}

type StraceParserImpl struct {
	lval  StraceSymType
	stack [StraceInitialStackSize]StraceSymType
	char  int
}

func (p *StraceParserImpl) Lookahead() int {
	return p.char
}

func StraceNewParser() StraceParser {
	return &StraceParserImpl{}
}

const StraceFlag = -1000

func StraceTokname(c int) string {
	if c >= 1 && c-1 < len(StraceToknames) {
		if StraceToknames[c-1] != "" {
			return StraceToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func StraceStatname(s int) string {
	if s >= 0 && s < len(StraceStatenames) {
		if StraceStatenames[s] != "" {
			return StraceStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func StraceErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !StraceErrorVerbose {
		return "syntax error"
	}

	for _, e := range StraceErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + StraceTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(StracePact[state])
	for tok := TOKSTART; tok-1 < len(StraceToknames); tok++ {
		if n := base + tok; n >= 0 && n < StraceLast && int(StraceChk[int(StraceAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if StraceDef[state] == -2 {
		i := 0
		for StraceExca[i] != -1 || int(StraceExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; StraceExca[i] >= 0; i += 2 {
			tok := int(StraceExca[i])
			if tok < TOKSTART || StraceExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if StraceExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += StraceTokname(tok)
	}
	return res
}

func Stracelex1(lex StraceLexer, lval *StraceSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(StraceTok1[0])
		goto out
	}
	if char < len(StraceTok1) {
		token = int(StraceTok1[char])
		goto out
	}
	if char >= StracePrivate {
		if char < StracePrivate+len(StraceTok2) {
			token = int(StraceTok2[char-StracePrivate])
			goto out
		}
	}
	for i := 0; i < len(StraceTok3); i += 2 {
		token = int(StraceTok3[i+0])
		if token == char {
			token = int(StraceTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(StraceTok2[1]) /* unknown char */
	}
	if StraceDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", StraceTokname(token), uint(char))
	}
	return char, token
}

func StraceParse(Stracelex StraceLexer) int {
	return StraceNewParser().Parse(Stracelex)
}

func (Stracercvr *StraceParserImpl) Parse(Stracelex StraceLexer) int {
	var Stracen int
	var StraceVAL StraceSymType
	var StraceDollar []StraceSymType
	_ = StraceDollar // silence set and not used
	StraceS := Stracercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Stracestate := 0
	Stracercvr.char = -1
	Stracetoken := -1 // Stracercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Stracestate = -1
		Stracercvr.char = -1
		Stracetoken = -1
	}()
	Stracep := -1
	goto Stracestack

ret0:
	return 0

ret1:
	return 1

Stracestack:
	/* put a state and value onto the stack */
	if StraceDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", StraceTokname(Stracetoken), StraceStatname(Stracestate))
	}

	Stracep++
	if Stracep >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceS[Stracep] = StraceVAL
	StraceS[Stracep].yys = Stracestate

Stracenewstate:
	Stracen = int(StracePact[Stracestate])
	if Stracen <= StraceFlag {
		goto Stracedefault /* simple state */
	}
	if Stracercvr.char < 0 {
		Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
	}
	Stracen += Stracetoken
	if Stracen < 0 || Stracen >= StraceLast {
		goto Stracedefault
	}
	Stracen = int(StraceAct[Stracen])
	if int(StraceChk[Stracen]) == Stracetoken { /* valid shift */
		Stracercvr.char = -1
		Stracetoken = -1
		StraceVAL = Stracercvr.lval
		Stracestate = Stracen
		if Errflag > 0 {
			Errflag--
		}
		goto Stracestack
	}

Stracedefault:
	/* default state action */
	Stracen = int(StraceDef[Stracestate])
	if Stracen == -2 {
		if Stracercvr.char < 0 {
			Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if StraceExca[xi+0] == -1 && int(StraceExca[xi+1]) == Stracestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Stracen = int(StraceExca[xi+0])
			if Stracen < 0 || Stracen == Stracetoken {
				break
			}
		}
		Stracen = int(StraceExca[xi+1])
		if Stracen < 0 {
			goto ret0
		}
	}
	if Stracen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Stracelex.Error(StraceErrorMessage(Stracestate, Stracetoken))
			Nerrs++
			if StraceDebug >= 1 {
				__yyfmt__.Printf("%s", StraceStatname(Stracestate))
				__yyfmt__.Printf(" saw %s\n", StraceTokname(Stracetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Stracep >= 0 {
				Stracen = int(StracePact[StraceS[Stracep].yys]) + StraceErrCode
				if Stracen >= 0 && Stracen < StraceLast {
					Stracestate = int(StraceAct[Stracen]) /* simulate a shift of "error" */
					if int(StraceChk[Stracestate]) == StraceErrCode {
						goto Stracestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if StraceDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", StraceS[Stracep].yys)
				}
				Stracep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if StraceDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", StraceTokname(Stracetoken))
			}
			if Stracetoken == StraceEofCode {
				goto ret1
			}
			Stracercvr.char = -1
			Stracetoken = -1
			goto Stracenewstate /* try again in the same state */
		}
	}

	/* reduction by production Stracen */
	if StraceDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Stracen, StraceStatname(Stracestate))
	}

	Stracent := Stracen
	Stracept := Stracep
	_ = Stracept // guard against "declared and not used"

	Stracep -= int(StraceR2[Stracen])
	// Stracep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Stracep+1 >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceVAL = StraceS[Stracep+1]

	/* consult goto table to find next state */
	Stracen = int(StraceR1[Stracen])
	Straceg := int(StracePgo[Stracen])
	Stracej := Straceg + StraceS[Stracep].yys + 1

	if Stracej >= StraceLast {
		Stracestate = int(StraceAct[Straceg])
	} else {
		Stracestate = int(StraceAct[Stracej])
		if int(StraceChk[Stracestate]) != -Stracen {
			Stracestate = int(StraceAct[Straceg])
		}
	}
	// dummy call; replaced with literal code
	switch Stracent {

	case 1:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:63
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(-1), true, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 2:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:66
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 3:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:71
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 4:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:76
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[6].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 5:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line strace.y:82
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[8].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 6:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:87
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 7:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line strace.y:89
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[7].val_types, StraceDollar[10].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 8:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:91
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, -1, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 9:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line strace.y:93
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 10:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:96
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 11:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:98
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 12:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:101
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, -1, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 13:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line strace.y:104
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 14:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:107
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 15:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:110
		{
			call := StraceDollar[2].val_syscall
			call.Pid = StraceDollar[1].val_int
			Stracelex.(*Stracelexer).result = call
		}
	case 16:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:113
		{
			StraceVAL.val_type = nil
		}
	case 17:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:114
		{
			StraceVAL.val_type = nil
		}
	case 18:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:117
		{
			StraceVAL.val_type = nil
		}
	case 19:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:118
		{
			StraceVAL.val_type = nil
		}
	case 20:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:119
		{
			StraceVAL.val_type = nil
		}
	case 21:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:120
		{
			StraceVAL.val_type = nil
		}
	case 22:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:121
		{
			StraceVAL.val_type = nil
		}
	case 23:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:122
		{
			StraceVAL.val_type = nil
		}
	case 24:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:123
		{
			StraceVAL.val_type = nil
		}
	case 25:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:124
		{
			StraceVAL.val_type = nil
		}
	case 26:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:125
		{
			StraceVAL.val_type = nil
		}
	case 27:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:126
		{
			StraceVAL.val_type = nil
		}
	case 28:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:127
		{
			StraceVAL.val_type = nil
		}
	case 29:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:130
		{
			StraceVAL.val_ret_type = StraceDollar[1].val_int
		}
	case 30:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:131
		{
			StraceVAL.val_ret_type = int64(StraceDollar[1].val_uint)
		}
	case 31:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:132
		{
			StraceVAL.val_ret_type = -1 * StraceDollar[2].val_int
		}
	case 32:
		StraceDollar = StraceS[Stracept-0 : Stracept+1]
//line strace.y:135
		{
			StraceVAL.val_types = []IrType{}
		}
	case 33:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:136
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 34:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:137
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[2].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 35:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:140
		{
			StraceVAL.val_type = StraceDollar[1].val_buf_type
		}
	case 36:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:141
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 37:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:142
		{
			StraceVAL.val_type = StraceDollar[1].val_group_type
		}
	case 38:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:143
		{
			StraceVAL.val_type = StraceDollar[1].val_constant
		}
	case 39:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:144
		{
			StraceVAL.val_type = StraceDollar[2].val_group_type
		}
	case 40:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:147
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_int)
		}
	case 41:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:148
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_uint)
		}
	case 42:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:149
		{
			StraceVAL.val_constant = Constant(uint64(0))
		}
	case 43:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:150
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 44:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:151
		{
			StraceVAL.val_constant = StraceDollar[2].val_constant
		}
	case 45:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:152
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant & StraceDollar[3].val_constant
		}
	case 46:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:153
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant << StraceDollar[3].val_constant
		}
	case 47:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:154
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant >> StraceDollar[3].val_constant
		}
	case 48:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:155
		{
			StraceVAL.val_constant = StraceDollar[2].val_constant
		}
	case 49:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:156
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant * StraceDollar[3].val_constant
		}
	case 50:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:157
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant - StraceDollar[3].val_constant
		}
	case 51:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:158
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant + StraceDollar[3].val_constant
		}
	case 52:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:159
		{
			StraceVAL.val_constant = ^StraceDollar[2].val_constant
		}
	case 53:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:160
		{
			StraceVAL.val_constant = Constant(-int64(StraceDollar[2].val_constant))
		}
	case 54:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:163
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 55:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:164
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 56:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:165
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 57:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:168
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 58:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:169
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 59:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:170
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 60:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:171
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 61:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:172
		{
			StraceVAL.val_type = StraceDollar[6].val_type
		}
	case 62:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:175
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 63:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:176
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 64:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:177
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 65:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:178
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 66:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:179
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	}
	goto Stracestack /* stack new state and value */
}
