// Code generated by goyacc -o strace.go -p Strace -v= strace.y. DO NOT EDIT.

//line strace.y:2

// Copyright 2018 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

// nolint
package parser

import __yyfmt__ "fmt"

//line strace.y:6
//line strace.y:12
type StraceSymType struct {
	yys             int
	data            string
	val_int         int64
	val_double      float64
	val_ret_type    int64
	val_uint        uint64
	val_constant    Constant
	val_identifiers []*BufferType
	val_buf_type    *BufferType
	val_group_type  *GroupType
	val_type        IrType
	val_types       []IrType
	val_syscall     *Syscall
}

const STRING_LITERAL = 57346
const IPV6 = 57347
const IDENTIFIER = 57348
const FLAG = 57349
const DATETIME = 57350
const SIGNAL_PLUS = 57351
const SIGNAL_MINUS = 57352
const MAC = 57353
const INT = 57354
const UINT = 57355
const DOUBLE = 57356
const QUESTION = 57357
const ARROW = 57358
const OR = 57359
const AND = 57360
const LOR = 57361
const TIMES = 57362
const LAND = 57363
const LEQUAL = 57364
const ONESCOMP = 57365
const LSHIFT = 57366
const RSHIFT = 57367
const NOT = 57368
const MINUS = 57369
const PLUS = 57370
const COMMA = 57371
const LBRACKET = 57372
const RBRACKET = 57373
const LBRACKET_SQUARE = 57374
const RBRACKET_SQUARE = 57375
const LPAREN = 57376
const RPAREN = 57377
const EQUALS = 57378
const UNFINISHED = 57379
const RESUMED = 57380
const NULL = 57381
const EQUALAT = 57382
const COLON = 57383
const FORWARDSLASH = 57384
const NOTYPE = 57385
const NOFLAG = 57386

var StraceToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING_LITERAL",
	"IPV6",
	"IDENTIFIER",
	"FLAG",
	"DATETIME",
	"SIGNAL_PLUS",
	"SIGNAL_MINUS",
	"MAC",
	"INT",
	"UINT",
	"DOUBLE",
	"QUESTION",
	"ARROW",
	"OR",
	"AND",
	"LOR",
	"TIMES",
	"LAND",
	"LEQUAL",
	"ONESCOMP",
	"LSHIFT",
	"RSHIFT",
	"NOT",
	"MINUS",
	"PLUS",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LBRACKET_SQUARE",
	"RBRACKET_SQUARE",
	"LPAREN",
	"RPAREN",
	"EQUALS",
	"UNFINISHED",
	"RESUMED",
	"NULL",
	"EQUALAT",
	"COLON",
	"FORWARDSLASH",
	"NOTYPE",
	"NOFLAG",
}
var StraceStatenames = [...]string{}

const StraceEofCode = 1
const StraceErrCode = 2
const StraceInitialStackSize = 16

//line yacctab:1
var StraceExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const StracePrivate = 57344

const StraceLast = 330

var StraceAct = [...]int{

	11, 8, 92, 75, 12, 31, 34, 33, 88, 33,
	91, 30, 73, 72, 42, 2, 54, 51, 43, 50,
	53, 4, 52, 28, 45, 106, 31, 89, 48, 49,
	33, 32, 55, 56, 57, 58, 59, 86, 104, 5,
	60, 61, 62, 63, 64, 65, 66, 3, 34, 43,
	30, 98, 101, 74, 90, 30, 29, 102, 103, 68,
	80, 40, 94, 95, 85, 69, 39, 70, 31, 96,
	97, 55, 33, 40, 93, 19, 82, 18, 87, 7,
	114, 39, 20, 21, 84, 26, 100, 99, 40, 41,
	105, 100, 100, 44, 109, 67, 10, 24, 46, 47,
	19, 107, 18, 9, 23, 100, 0, 100, 100, 22,
	109, 100, 100, 109, 109, 110, 0, 111, 98, 101,
	77, 78, 0, 83, 102, 103, 1, 98, 101, 94,
	95, 25, 0, 102, 103, 79, 96, 97, 94, 95,
	0, 93, 19, 0, 18, 96, 97, 113, 0, 0,
	93, 19, 0, 18, 99, 0, 112, 0, 98, 101,
	0, 0, 0, 99, 102, 103, 0, 98, 101, 94,
	95, 0, 0, 102, 103, 0, 96, 97, 94, 95,
	0, 93, 19, 0, 18, 96, 97, 108, 0, 0,
	93, 19, 0, 18, 99, 0, 0, 14, 0, 15,
	0, 16, 0, 99, 17, 20, 21, 0, 0, 0,
	14, 0, 15, 0, 16, 0, 13, 17, 20, 21,
	24, 0, 0, 19, 81, 18, 0, 23, 0, 13,
	0, 0, 22, 24, 77, 78, 19, 76, 18, 14,
	23, 15, 0, 16, 27, 22, 17, 20, 21, 79,
	0, 0, 14, 0, 15, 0, 16, 0, 13, 17,
	20, 21, 24, 0, 0, 19, 0, 18, 0, 23,
	0, 13, 6, 0, 22, 24, 0, 0, 19, 0,
	18, 0, 23, 20, 21, 35, 36, 22, 39, 0,
	0, 0, 37, 38, 44, 40, 41, 0, 24, 0,
	0, 35, 36, 71, 39, 23, 0, 0, 37, 38,
	22, 40, 41, 36, 0, 39, 0, 0, 0, 37,
	38, 39, 40, 41, 0, 37, 38, 0, 40, 41,
}
var StracePact = [...]int{

	9, -1000, 5, 235, 9, 206, -12, 21, -10, -1000,
	-1000, -1000, 284, 70, -1000, -8, -1000, -1000, 248, 248,
	-1000, -1000, -1000, 271, 271, -1000, -18, -13, -16, -20,
	248, 248, 248, 248, 248, 271, 271, 271, 271, 271,
	271, 271, -1000, -1000, 271, 88, 26, 36, 268, -1000,
	-1000, -23, -24, 38, 222, -10, -33, 32, -1000, -31,
	295, 301, 61, 61, 34, -1000, 46, 27, -1000, 193,
	-1000, -1000, 108, 72, -1000, 30, -1000, -1000, -1000, 66,
	-28, -1000, 20, -1000, -1000, 161, 4, -1000, 248, -9,
	161, 152, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 161, -33, 161, 121, -1000, -1000,
	112, 45, -1000, -1000, -1000,
}
var StracePgo = [...]int{

	0, 126, 3, 103, 0, 4, 2, 10, 1, 96,
	79,
}
var StraceR1 = [...]int{

	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 7, 7, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 2, 2, 2, 10,
	10, 10, 8, 8, 8, 8, 8, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	4, 4, 4, 9, 9, 9, 9, 9, 9, 3,
	3, 3, 3,
}
var StraceR2 = [...]int{

	0, 4, 5, 6, 5, 5, 8, 9, 6, 6,
	10, 9, 2, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 0,
	1, 3, 1, 1, 1, 1, 2, 1, 1, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 2,
	3, 3, 4, 2, 3, 3, 3, 3, 6, 1,
	1, 1, 1,
}
var StraceChk = [...]int{

	-1000, -1, 6, 38, 12, 34, 37, -10, -8, -3,
	-9, -4, -5, 23, 4, 6, 8, 11, 32, 30,
	12, 13, 39, 34, 27, -1, -10, 38, 35, 35,
	29, 36, 41, 40, 16, 17, 18, 24, 25, 20,
	27, 28, -4, -5, 23, 32, -10, -10, -5, -5,
	37, 35, 35, 36, 36, -8, -8, -8, -8, -8,
	-5, -5, -5, -5, -5, -5, -5, 7, 33, 29,
	31, 35, 36, 36, 15, -2, 15, 12, 13, 27,
	33, 31, -2, 15, 12, 34, 7, 12, 36, 7,
	34, -7, -6, 29, 17, 18, 24, 25, 6, 42,
	-4, 7, 12, 13, 34, -8, 34, -7, 35, -6,
	-7, -7, 35, 35, 35,
}
var StraceDef = [...]int{

	0, -2, 0, 29, 0, 29, 0, 0, 30, 32,
	33, 34, 35, 0, 59, 60, 61, 62, 29, 29,
	37, 38, 39, 0, 0, 12, 0, 0, 0, 0,
	0, 53, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 36, 48, 0, 0, 0, 0, 0, 49,
	1, 0, 0, 0, 0, 31, 56, 54, 55, 57,
	40, 41, 42, 43, 45, 46, 47, 0, 50, 0,
	51, 44, 0, 0, 2, 4, 5, 26, 27, 0,
	0, 52, 8, 9, 3, 0, 0, 28, 0, 0,
	0, 0, 13, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 0, 58, 0, 0, 6, 14,
	0, 0, 11, 7, 10,
}
var StraceTok1 = [...]int{

	1,
}
var StraceTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44,
}
var StraceTok3 = [...]int{
	0,
}

var StraceErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	StraceDebug        = 0
	StraceErrorVerbose = false
)

type StraceLexer interface {
	Lex(lval *StraceSymType) int
	Error(s string)
}

type StraceParser interface {
	Parse(StraceLexer) int
	Lookahead() int
}

type StraceParserImpl struct {
	lval  StraceSymType
	stack [StraceInitialStackSize]StraceSymType
	char  int
}

func (p *StraceParserImpl) Lookahead() int {
	return p.char
}

func StraceNewParser() StraceParser {
	return &StraceParserImpl{}
}

const StraceFlag = -1000

func StraceTokname(c int) string {
	if c >= 1 && c-1 < len(StraceToknames) {
		if StraceToknames[c-1] != "" {
			return StraceToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func StraceStatname(s int) string {
	if s >= 0 && s < len(StraceStatenames) {
		if StraceStatenames[s] != "" {
			return StraceStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func StraceErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !StraceErrorVerbose {
		return "syntax error"
	}

	for _, e := range StraceErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + StraceTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := StracePact[state]
	for tok := TOKSTART; tok-1 < len(StraceToknames); tok++ {
		if n := base + tok; n >= 0 && n < StraceLast && StraceChk[StraceAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if StraceDef[state] == -2 {
		i := 0
		for StraceExca[i] != -1 || StraceExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; StraceExca[i] >= 0; i += 2 {
			tok := StraceExca[i]
			if tok < TOKSTART || StraceExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if StraceExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += StraceTokname(tok)
	}
	return res
}

func Stracelex1(lex StraceLexer, lval *StraceSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = StraceTok1[0]
		goto out
	}
	if char < len(StraceTok1) {
		token = StraceTok1[char]
		goto out
	}
	if char >= StracePrivate {
		if char < StracePrivate+len(StraceTok2) {
			token = StraceTok2[char-StracePrivate]
			goto out
		}
	}
	for i := 0; i < len(StraceTok3); i += 2 {
		token = StraceTok3[i+0]
		if token == char {
			token = StraceTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = StraceTok2[1] /* unknown char */
	}
	if StraceDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", StraceTokname(token), uint(char))
	}
	return char, token
}

func StraceParse(Stracelex StraceLexer) int {
	return StraceNewParser().Parse(Stracelex)
}

func (Stracercvr *StraceParserImpl) Parse(Stracelex StraceLexer) int {
	var Stracen int
	var StraceVAL StraceSymType
	var StraceDollar []StraceSymType
	_ = StraceDollar // silence set and not used
	StraceS := Stracercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Stracestate := 0
	Stracercvr.char = -1
	Stracetoken := -1 // Stracercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Stracestate = -1
		Stracercvr.char = -1
		Stracetoken = -1
	}()
	Stracep := -1
	goto Stracestack

ret0:
	return 0

ret1:
	return 1

Stracestack:
	/* put a state and value onto the stack */
	if StraceDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", StraceTokname(Stracetoken), StraceStatname(Stracestate))
	}

	Stracep++
	if Stracep >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceS[Stracep] = StraceVAL
	StraceS[Stracep].yys = Stracestate

Stracenewstate:
	Stracen = StracePact[Stracestate]
	if Stracen <= StraceFlag {
		goto Stracedefault /* simple state */
	}
	if Stracercvr.char < 0 {
		Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
	}
	Stracen += Stracetoken
	if Stracen < 0 || Stracen >= StraceLast {
		goto Stracedefault
	}
	Stracen = StraceAct[Stracen]
	if StraceChk[Stracen] == Stracetoken { /* valid shift */
		Stracercvr.char = -1
		Stracetoken = -1
		StraceVAL = Stracercvr.lval
		Stracestate = Stracen
		if Errflag > 0 {
			Errflag--
		}
		goto Stracestack
	}

Stracedefault:
	/* default state action */
	Stracen = StraceDef[Stracestate]
	if Stracen == -2 {
		if Stracercvr.char < 0 {
			Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if StraceExca[xi+0] == -1 && StraceExca[xi+1] == Stracestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Stracen = StraceExca[xi+0]
			if Stracen < 0 || Stracen == Stracetoken {
				break
			}
		}
		Stracen = StraceExca[xi+1]
		if Stracen < 0 {
			goto ret0
		}
	}
	if Stracen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Stracelex.Error(StraceErrorMessage(Stracestate, Stracetoken))
			Nerrs++
			if StraceDebug >= 1 {
				__yyfmt__.Printf("%s", StraceStatname(Stracestate))
				__yyfmt__.Printf(" saw %s\n", StraceTokname(Stracetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Stracep >= 0 {
				Stracen = StracePact[StraceS[Stracep].yys] + StraceErrCode
				if Stracen >= 0 && Stracen < StraceLast {
					Stracestate = StraceAct[Stracen] /* simulate a shift of "error" */
					if StraceChk[Stracestate] == StraceErrCode {
						goto Stracestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if StraceDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", StraceS[Stracep].yys)
				}
				Stracep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if StraceDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", StraceTokname(Stracetoken))
			}
			if Stracetoken == StraceEofCode {
				goto ret1
			}
			Stracercvr.char = -1
			Stracetoken = -1
			goto Stracenewstate /* try again in the same state */
		}
	}

	/* reduction by production Stracen */
	if StraceDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Stracen, StraceStatname(Stracestate))
	}

	Stracent := Stracen
	Stracept := Stracep
	_ = Stracept // guard against "declared and not used"

	Stracep -= StraceR2[Stracen]
	// Stracep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Stracep+1 >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceVAL = StraceS[Stracep+1]

	/* consult goto table to find next state */
	Stracen = StraceR1[Stracen]
	Straceg := StracePgo[Stracen]
	Stracej := Straceg + StraceS[Stracep].yys + 1

	if Stracej >= StraceLast {
		Stracestate = StraceAct[Straceg]
	} else {
		Stracestate = StraceAct[Stracej]
		if StraceChk[Stracestate] != -Stracen {
			Stracestate = StraceAct[Straceg]
		}
	}
	// dummy call; replaced with literal code
	switch Stracent {

	case 1:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:63
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(-1), true, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 2:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:66
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 3:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:71
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[6].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 4:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:76
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 5:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:78
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, -1, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 6:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line strace.y:80
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 7:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:83
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 8:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:85
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 9:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:88
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, -1, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 10:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line strace.y:91
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 11:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:94
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 12:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:97
		{
			call := StraceDollar[2].val_syscall
			call.Pid = StraceDollar[1].val_int
			Stracelex.(*Stracelexer).result = call
		}
	case 13:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:100
		{
			StraceVAL.val_type = nil
		}
	case 14:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:101
		{
			StraceVAL.val_type = nil
		}
	case 15:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:104
		{
			StraceVAL.val_type = nil
		}
	case 16:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:105
		{
			StraceVAL.val_type = nil
		}
	case 17:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:106
		{
			StraceVAL.val_type = nil
		}
	case 18:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:107
		{
			StraceVAL.val_type = nil
		}
	case 19:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:108
		{
			StraceVAL.val_type = nil
		}
	case 20:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:109
		{
			StraceVAL.val_type = nil
		}
	case 21:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:110
		{
			StraceVAL.val_type = nil
		}
	case 22:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:111
		{
			StraceVAL.val_type = nil
		}
	case 23:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:112
		{
			StraceVAL.val_type = nil
		}
	case 24:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:113
		{
			StraceVAL.val_type = nil
		}
	case 25:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:114
		{
			StraceVAL.val_type = nil
		}
	case 26:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:117
		{
			StraceVAL.val_ret_type = StraceDollar[1].val_int
		}
	case 27:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:118
		{
			StraceVAL.val_ret_type = int64(StraceDollar[1].val_uint)
		}
	case 28:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:119
		{
			StraceVAL.val_ret_type = -1 * StraceDollar[2].val_int
		}
	case 29:
		StraceDollar = StraceS[Stracept-0 : Stracept+1]
//line strace.y:121
		{
			StraceVAL.val_types = make([]IrType, 0)
		}
	case 30:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:122
		{
			StraceVAL.val_types = []IrType{StraceDollar[1].val_type}
		}
	case 31:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:123
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 32:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:126
		{
			StraceVAL.val_type = StraceDollar[1].val_buf_type
		}
	case 33:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:127
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 34:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:128
		{
			StraceVAL.val_type = StraceDollar[1].val_group_type
		}
	case 35:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:129
		{
			StraceVAL.val_type = StraceDollar[1].val_constant
		}
	case 36:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:130
		{
			StraceVAL.val_type = StraceDollar[2].val_group_type
		}
	case 37:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:133
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_int)
		}
	case 38:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:134
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_uint)
		}
	case 39:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:135
		{
			StraceVAL.val_constant = Constant(uint64(0))
		}
	case 40:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:136
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 41:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:137
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant & StraceDollar[3].val_constant
		}
	case 42:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:138
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant << StraceDollar[3].val_constant
		}
	case 43:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:139
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant >> StraceDollar[3].val_constant
		}
	case 44:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:140
		{
			StraceVAL.val_constant = StraceDollar[2].val_constant
		}
	case 45:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:141
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant * StraceDollar[3].val_constant
		}
	case 46:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:142
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant - StraceDollar[3].val_constant
		}
	case 47:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:143
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant + StraceDollar[3].val_constant
		}
	case 48:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:144
		{
			StraceVAL.val_constant = ^StraceDollar[2].val_constant
		}
	case 49:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:145
		{
			StraceVAL.val_constant = Constant(-int64(StraceDollar[2].val_constant))
		}
	case 50:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:148
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 51:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:149
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 52:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:150
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 53:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:153
		{
			StraceVAL.val_type = nil
		}
	case 54:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:154
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 55:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:155
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 56:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:156
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 57:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:157
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 58:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:158
		{
			StraceVAL.val_type = StraceDollar[6].val_type
		}
	case 59:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:161
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 60:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:162
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 61:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:163
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 62:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:164
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	}
	goto Stracestack /* stack new state and value */
}
