// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewRow creates a new instance of Row. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *Row {
	mock := &Row{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Row is an autogenerated mock type for the Row type
type Row struct {
	mock.Mock
}

type Row_Expecter struct {
	mock *mock.Mock
}

func (_m *Row) EXPECT() *Row_Expecter {
	return &Row_Expecter{mock: &_m.Mock}
}

// ToStruct provides a mock function for the type Row
func (_mock *Row) ToStruct(p any) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for ToStruct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Row_ToStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToStruct'
type Row_ToStruct_Call struct {
	*mock.Call
}

// ToStruct is a helper method to define mock.On call
//   - p any
func (_e *Row_Expecter) ToStruct(p interface{}) *Row_ToStruct_Call {
	return &Row_ToStruct_Call{Call: _e.mock.On("ToStruct", p)}
}

func (_c *Row_ToStruct_Call) Run(run func(p any)) *Row_ToStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Row_ToStruct_Call) Return(err error) *Row_ToStruct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Row_ToStruct_Call) RunAndReturn(run func(p any) error) *Row_ToStruct_Call {
	_c.Call.Return(run)
	return _c
}
