# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.6.2/install.yaml
  - workflow-roles.yaml

patchesStrategicMerge:
  - patch-argo-controller.yaml
  - patch-workflow-controller-configmap.yaml
