# Copyright 2020 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

# See https://docs.codecov.io/docs/codecovyml-reference
# Validate with curl --data-binary @tools/codecov.yml https://codecov.io/validate

coverage:
  precision: 0
  round: nearest
  range: "50...75"

coverage:
  status:
    project:
      default:
        threshold: 1%
