// AUTOGENERATED FILE
package fuchsia

import . "github.com/google/syzkaller/prog"

func init() {
	RegisterTarget(&Target{OS: "fuchsia", Arch: "amd64", Revision: revision_amd64, PtrSize: 8, Syscalls: syscalls_amd64, Resources: resources_amd64, Structs: structDescs_amd64, Consts: consts_amd64}, initTarget)
}

var resources_amd64 = []*ResourceDesc(nil)

var structDescs_amd64 = []*KeyedStruct(nil)

var syscalls_amd64 = []*Syscall{
	{Name: "mx_time_get", CallName: "mx_time_get", Args: []Type{
		&FlagsType{IntTypeCommon: IntTypeCommon{TypeCommon: TypeCommon{TypeName: "clock_id", FldName: "clock_id", TypeSize: 8}}, Vals: []uint64{0, 1, 2}},
	}},
}

var consts_amd64 = []ConstValue{
	{Name: "MX_CLOCK_MONOTONIC"},
	{Name: "MX_CLOCK_THREAD", Value: 2},
	{Name: "MX_CLOCK_UTC", Value: 1},
	{Name: "__NR_mx_time_get"},
}

const revision_amd64 = "d65b9adb4853817be6f471df44fc8347ebf6dfc6"
