# Copyright 2023 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

# https://github.com/actions/stale for details.

name: 'Label/close stale PRs'
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity.'
          days-before-pr-stale: 90
          days-before-pr-close: -1 # never
