name: CSB actions
on: [workflow_dispatch, push, pull_request]

jobs:
   Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [syz-trace2syz, syz-prog2c, syz-extraction]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Compile syzkaller
        run: |
          make
      - name: Compile ${{ matrix.tool }}
        run: |
          go env -w GOBIN=$HOME/.local/bin
          cd tools/${{ matrix.tool }}
          go build
