name: CIFuzz

on: [pull_request]

jobs:
  Fuzzing:

    runs-on: ubuntu-latest

    steps:
    - name: Building and running fuzzers
      uses: Leo-Neat/oss-fuzz/infra/cifuzz/actions@master
      with:
        project-name: 'syzkaller'
        fuzz-seconds: 3600
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: fuzzer_testcase
        path: ./out/testcase
